0321 Django Static & Media/Course Material/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    # path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    # path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update', views.update, name='update'),
]

0321 Django Static & Media/Course Material/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()

    image = models.ImageField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}번째글 - {self.title}'

0321 Django Static & Media/Course Material/articles/forms.py
from django import forms
from .models import Article

# class ArticleForm(forms.Form):
#     title = forms.CharField(max_length=30)
#     content = forms.CharField(widget=forms.Textarea)

class ArticleForm(forms.ModelForm):

    title = forms.CharField(
        label='제목',
        widget=forms.TextInput(
            attrs={
                'class': 'my-title',
                'placeholder': 'Enter the title',
            }
        ),
    )

    class Meta:
        model = Article
        fields = '__all__'

0321 Django Static & Media/Course Material/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm

# Create your views here.

def index(request):

    articles = Article.objects.all()
    context = {'articles': articles}

    return render(request, 'articles/index.html', context)

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {'article': article}

    return render(request, 'articles/detail.html', context)

# def new(request):
#     return render(request, 'articles/new.html')

def create(request):


    if request.method == 'POST': # 게시글 작성 요청
        form = ArticleForm(request.POST, request.FILES)
        
        if form.is_valid():
            # print('#'*80)
            # print(form.cleaned_data)
            # print('#'*80)
            article = form.save()
            return redirect('articles:detail', article.pk)
        
        # title = request.POST.get('title')
        # content = request.POST.get('content')

        # # # DB에 새로운 Article 저장
        # # Article.objects.create(
        # #     title=title,
        # #     content=content
        # # )

        # article = Article(title=title, content=content)
        # # ~~~~~~~~~~~~
        # article.save()

        
    
    else: # 게시글 작성 페이지 요청
        form = ArticleForm()
    
    context = {'form': form}
    return render(request, 'articles/create.html', context)
    
        

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('articles:index')

# def edit(request, pk):
#     article = Article.objects.get(pk=pk)
#     context = {
#         'article': article,
#     }
#     return render(request, 'articles/edit.html', context)

def update(request, pk):
    article = Article.objects.get(pk=pk)

    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save() # 이미 위에서 받고 있으니, 굳이 받을 필요 X
            return redirect('articles:detail', article.pk)

        # article.title = request.POST.get('title')
        # article.content = request.POST.get('content')
        # article.save()
        # return redirect('articles:detail', article.pk)
    
    else:
        # 비어 있는 form이 아니라 기존의 article을 채운 form 이어야함
        form = ArticleForm(instance=article)


    # context = {
    #     'article': article,
    # }
    
    context = {
        'form': form,
        'article': article,
    }
    return render(request, 'articles/update.html', context)

0321 Django Static & Media/Course Material/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>CREATE</h1>
  <hr>

  <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    {% comment %} <label for="title">제목 : </label>
    <input type="text" id="title" name="title">

    <br>

    <label for="content">내용 : </label>
    <input type="text" id="content" name="content">

    <br>

    {% endcomment %}

    {{ form.as_p }}
    <input type="submit"> 

  </form>
  <hr>
  <a href="{% url 'articles:index' %}">[back]</a>


{% endblock content %}

0321 Django Static & Media/Course Material/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <br>
  {% if article.image %}
    <img src="{{ article.image.url }}" alt="{{ article.image }}">
  {% endif %}
  
  <h1>DETAIL</h1>
  <hr>

  <p>글 제목: {{article.title}}</p>
  <p>글 내용: {{article.content}}</p>
  <p>생성시각: {{article.created_at}}</p>
  <p>수정시각: {{article.updated_at}}</p>
  

  <a href="{% url 'articles:index' %}">목록보기 </a>

  <br>
  <hr>
  <a href="{% url 'articles:update' article.pk %}">UPDATE</a>
  <br>

  <form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="DELETE">
  </form>
  <br>
  <a href="{% url 'articles:index' %}">[back]</a>

{% endblock content %}

0321 Django Static & Media/Course Material/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>INDEX</h1>

  {% for article in articles %}
    <p>글 번호 : {{article.id}}</p>
    <p><a href="{% url 'articles:detail' article.pk %}"> 글 제목 : {{article.title}}</a></p>
    <p>글 내용 : {{article.content}}</p>
    <hr>
  {% endfor %}

  <a href="{% url 'articles:create' %}">CREATE</a>
  <hr>

{% endblock content %}

0321 Django Static & Media/Course Material/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>


  <form action="{% url 'articles:update' article.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    {% comment %} <label for="title">제목 : </label>
    <input type="text" id="title" name="title" value="{{ article.title }}">

    <br>

    <label for="content">내용 : </label>
    <input type="text" id="content" name="content" value="{{ article.content }}">

    <br> {% endcomment %}

    {{form.as_p}}

    <input type="submit">
  </form>



  <hr>
  <a href="{% url 'articles:index' %}">[back]</a>
  

{% endblock content %}