0316 Django Model & ORM/course_material/articles/urls.py
from django.urls import path
from . import views

app_name='articles'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    path('create_article/', views.create_article, name='create_article'),
]

0316 Django Model & ORM/course_material/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

0316 Django Model & ORM/course_material/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()

0316 Django Model & ORM/course_material/articles/views.py
from django.shortcuts import render
from .models import Article

# Create your views here.
def index(request):
    articles = Article.objects.all()
    print(articles)
    context = {
        'articles': articles,
    }

    return render(request, 'articles/index.html', context)


def throw(request):
    return render(request, 'articles/throw.html')


def catch(request):
    message = request.GET.get('message')
    print(message)

    context = {
        'message': message,
    }

    return render(request, 'articles/catch.html', context)


def create_article(request):

    title = request.GET.get('title')
    content = request.GET.get('content')

    article = Article(title=title, content=content)
    article.save()

    return render(request, 'articles/create_article.html')

0316 Django Model & ORM/course_material/articles/templates/articles/catch.html
{% extends 'base.html' %}

{% block content %}

  <h1>Catch</h1>

  <h2>보낸 데이터 : {{ message }} </h2>

  <a href="{% url 'articles:throw' %}">다시 데이터 보내러가기</a>


{% endblock content %}

0316 Django Model & ORM/course_material/articles/templates/articles/create_article.html
{% extends 'base.html' %}

{% block content %}


  

  <a href="{% url 'articles:index' %}">다시 데이터 넣으러가기</a>


{% endblock content %}

0316 Django Model & ORM/course_material/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}

  <ul>
    {% for article in articles %}
      <li>{{ article.id }} {{ article.title }} {{ article.content }}</li>
    {% endfor %}
  </ul>


  <h1>여기는 인덱스입니다.</h1>

  <form action={% url 'articles:create_article' %} method="GET">
    <label for="title">title</label>
    <input type="text" id="title" name="title">
    {% comment %} <input type="submit"> {% endcomment %}
    <br>

    <label for="content">content</label>
    <input type="text" id="content" name="content">
    <input type="submit">
  </form>






{% endblock content %}

0316 Django Model & ORM/course_material/articles/templates/articles/throw.html
{% extends 'base.html' %}

{% block content %}

  <h1>Throw</h1>

  <form action={% url 'articles:catch' %} method="GET">
    <label for="message">보내고 싶은 데이터 적기</label>
    <input type="text" id="message" name="message">
    <input type="submit">
  </form>



{% endblock content %}

0316 Django Model & ORM/course_material/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Django 03</title>
</head>
<body>
  
  {% block content %}
  
  
  
  {% endblock content %}


</body>
</html>